### ISSUE TITLE
Add pickone method

### ISSUE THREAD

**Issue by rzschech** [davitv/chance#2]
I often want to pick one from a collection of values. Can we have a method similar to http://chancejs.com/#pickone

For example:

```
def pickone(list):
  return list[random.randint(1, len(list) - 1)]
```

Thanks

**Comment by davitv** [comment]
Thanks for suggestion! Added pickone method and uploaded new release to PyPi.

**Comment by rzschech** [comment]
Nice one, thanks :-)
